// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.1
// source: digitaltwin/conversation/v1/conversation.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Timestamp } from "../../../google/protobuf/timestamp";

export const protobufPackage = "digitaltwin.conversation.v1";

export enum Role {
  ROLE_UNSPECIFIED = "ROLE_UNSPECIFIED",
  ROLE_USER = "ROLE_USER",
  ROLE_ASSISTANT = "ROLE_ASSISTANT",
  ROLE_SYSTEM = "ROLE_SYSTEM",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export function roleFromJSON(object: any): Role {
  switch (object) {
    case 0:
    case "ROLE_UNSPECIFIED":
      return Role.ROLE_UNSPECIFIED;
    case 1:
    case "ROLE_USER":
      return Role.ROLE_USER;
    case 2:
    case "ROLE_ASSISTANT":
      return Role.ROLE_ASSISTANT;
    case 3:
    case "ROLE_SYSTEM":
      return Role.ROLE_SYSTEM;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Role.UNRECOGNIZED;
  }
}

export function roleToJSON(object: Role): string {
  switch (object) {
    case Role.ROLE_UNSPECIFIED:
      return "ROLE_UNSPECIFIED";
    case Role.ROLE_USER:
      return "ROLE_USER";
    case Role.ROLE_ASSISTANT:
      return "ROLE_ASSISTANT";
    case Role.ROLE_SYSTEM:
      return "ROLE_SYSTEM";
    case Role.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export function roleToNumber(object: Role): number {
  switch (object) {
    case Role.ROLE_UNSPECIFIED:
      return 0;
    case Role.ROLE_USER:
      return 1;
    case Role.ROLE_ASSISTANT:
      return 2;
    case Role.ROLE_SYSTEM:
      return 3;
    case Role.UNRECOGNIZED:
    default:
      return -1;
  }
}

export enum ConversationStatus {
  CONVERSATION_STATUS_UNSPECIFIED = "CONVERSATION_STATUS_UNSPECIFIED",
  CONVERSATION_STATUS_ACTIVE = "CONVERSATION_STATUS_ACTIVE",
  CONVERSATION_STATUS_ENDED = "CONVERSATION_STATUS_ENDED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export function conversationStatusFromJSON(object: any): ConversationStatus {
  switch (object) {
    case 0:
    case "CONVERSATION_STATUS_UNSPECIFIED":
      return ConversationStatus.CONVERSATION_STATUS_UNSPECIFIED;
    case 1:
    case "CONVERSATION_STATUS_ACTIVE":
      return ConversationStatus.CONVERSATION_STATUS_ACTIVE;
    case 2:
    case "CONVERSATION_STATUS_ENDED":
      return ConversationStatus.CONVERSATION_STATUS_ENDED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ConversationStatus.UNRECOGNIZED;
  }
}

export function conversationStatusToJSON(object: ConversationStatus): string {
  switch (object) {
    case ConversationStatus.CONVERSATION_STATUS_UNSPECIFIED:
      return "CONVERSATION_STATUS_UNSPECIFIED";
    case ConversationStatus.CONVERSATION_STATUS_ACTIVE:
      return "CONVERSATION_STATUS_ACTIVE";
    case ConversationStatus.CONVERSATION_STATUS_ENDED:
      return "CONVERSATION_STATUS_ENDED";
    case ConversationStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export function conversationStatusToNumber(object: ConversationStatus): number {
  switch (object) {
    case ConversationStatus.CONVERSATION_STATUS_UNSPECIFIED:
      return 0;
    case ConversationStatus.CONVERSATION_STATUS_ACTIVE:
      return 1;
    case ConversationStatus.CONVERSATION_STATUS_ENDED:
      return 2;
    case ConversationStatus.UNRECOGNIZED:
    default:
      return -1;
  }
}

export enum EmotionalTone {
  EMOTIONAL_TONE_UNSPECIFIED = "EMOTIONAL_TONE_UNSPECIFIED",
  EMOTIONAL_TONE_NEUTRAL = "EMOTIONAL_TONE_NEUTRAL",
  EMOTIONAL_TONE_HAPPY = "EMOTIONAL_TONE_HAPPY",
  EMOTIONAL_TONE_SAD = "EMOTIONAL_TONE_SAD",
  EMOTIONAL_TONE_ANGRY = "EMOTIONAL_TONE_ANGRY",
  EMOTIONAL_TONE_ANXIOUS = "EMOTIONAL_TONE_ANXIOUS",
  EMOTIONAL_TONE_SURPRISED = "EMOTIONAL_TONE_SURPRISED",
  EMOTIONAL_TONE_CALM = "EMOTIONAL_TONE_CALM",
  EMOTIONAL_TONE_EXCITED = "EMOTIONAL_TONE_EXCITED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export function emotionalToneFromJSON(object: any): EmotionalTone {
  switch (object) {
    case 0:
    case "EMOTIONAL_TONE_UNSPECIFIED":
      return EmotionalTone.EMOTIONAL_TONE_UNSPECIFIED;
    case 1:
    case "EMOTIONAL_TONE_NEUTRAL":
      return EmotionalTone.EMOTIONAL_TONE_NEUTRAL;
    case 2:
    case "EMOTIONAL_TONE_HAPPY":
      return EmotionalTone.EMOTIONAL_TONE_HAPPY;
    case 3:
    case "EMOTIONAL_TONE_SAD":
      return EmotionalTone.EMOTIONAL_TONE_SAD;
    case 4:
    case "EMOTIONAL_TONE_ANGRY":
      return EmotionalTone.EMOTIONAL_TONE_ANGRY;
    case 5:
    case "EMOTIONAL_TONE_ANXIOUS":
      return EmotionalTone.EMOTIONAL_TONE_ANXIOUS;
    case 6:
    case "EMOTIONAL_TONE_SURPRISED":
      return EmotionalTone.EMOTIONAL_TONE_SURPRISED;
    case 7:
    case "EMOTIONAL_TONE_CALM":
      return EmotionalTone.EMOTIONAL_TONE_CALM;
    case 8:
    case "EMOTIONAL_TONE_EXCITED":
      return EmotionalTone.EMOTIONAL_TONE_EXCITED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return EmotionalTone.UNRECOGNIZED;
  }
}

export function emotionalToneToJSON(object: EmotionalTone): string {
  switch (object) {
    case EmotionalTone.EMOTIONAL_TONE_UNSPECIFIED:
      return "EMOTIONAL_TONE_UNSPECIFIED";
    case EmotionalTone.EMOTIONAL_TONE_NEUTRAL:
      return "EMOTIONAL_TONE_NEUTRAL";
    case EmotionalTone.EMOTIONAL_TONE_HAPPY:
      return "EMOTIONAL_TONE_HAPPY";
    case EmotionalTone.EMOTIONAL_TONE_SAD:
      return "EMOTIONAL_TONE_SAD";
    case EmotionalTone.EMOTIONAL_TONE_ANGRY:
      return "EMOTIONAL_TONE_ANGRY";
    case EmotionalTone.EMOTIONAL_TONE_ANXIOUS:
      return "EMOTIONAL_TONE_ANXIOUS";
    case EmotionalTone.EMOTIONAL_TONE_SURPRISED:
      return "EMOTIONAL_TONE_SURPRISED";
    case EmotionalTone.EMOTIONAL_TONE_CALM:
      return "EMOTIONAL_TONE_CALM";
    case EmotionalTone.EMOTIONAL_TONE_EXCITED:
      return "EMOTIONAL_TONE_EXCITED";
    case EmotionalTone.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export function emotionalToneToNumber(object: EmotionalTone): number {
  switch (object) {
    case EmotionalTone.EMOTIONAL_TONE_UNSPECIFIED:
      return 0;
    case EmotionalTone.EMOTIONAL_TONE_NEUTRAL:
      return 1;
    case EmotionalTone.EMOTIONAL_TONE_HAPPY:
      return 2;
    case EmotionalTone.EMOTIONAL_TONE_SAD:
      return 3;
    case EmotionalTone.EMOTIONAL_TONE_ANGRY:
      return 4;
    case EmotionalTone.EMOTIONAL_TONE_ANXIOUS:
      return 5;
    case EmotionalTone.EMOTIONAL_TONE_SURPRISED:
      return 6;
    case EmotionalTone.EMOTIONAL_TONE_CALM:
      return 7;
    case EmotionalTone.EMOTIONAL_TONE_EXCITED:
      return 8;
    case EmotionalTone.UNRECOGNIZED:
    default:
      return -1;
  }
}

export interface StartConversationRequest {
  userId: string;
  title: string;
}

export interface StartConversationResponse {
  conversationId: string;
}

export interface SendMessageRequest {
  conversationId: string;
  body: string;
}

export interface SendMessageResponse {
  reply: string;
  tone: EmotionalTone;
}

export interface EndConversationRequest {
  conversationId: string;
}

export interface EndConversationResponse {
}

export interface GetHistoryRequest {
  conversationId: string;
  limit: number;
}

export interface GetHistoryResponse {
  messages: Message[];
}

export interface ListConversationsRequest {
  userId: string;
  limit: number;
}

export interface ListConversationsResponse {
  conversations: ConversationSummary[];
}

export interface Message {
  id: string;
  role: Role;
  body: string;
  tone: EmotionalTone;
  sentAt?: string | undefined;
}

export interface ConversationSummary {
  id: string;
  userId: string;
  title: string;
  status: ConversationStatus;
  messageCount: number;
  startedAt?: string | undefined;
  endedAt?: string | undefined;
}

function createBaseStartConversationRequest(): StartConversationRequest {
  return { userId: "", title: "" };
}

export const StartConversationRequest: MessageFns<StartConversationRequest> = {
  encode(message: StartConversationRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.title !== "") {
      writer.uint32(18).string(message.title);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StartConversationRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStartConversationRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.title = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StartConversationRequest {
    return {
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      title: isSet(object.title) ? globalThis.String(object.title) : "",
    };
  },

  toJSON(message: StartConversationRequest): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StartConversationRequest>, I>>(base?: I): StartConversationRequest {
    return StartConversationRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StartConversationRequest>, I>>(object: I): StartConversationRequest {
    const message = createBaseStartConversationRequest();
    message.userId = object.userId ?? "";
    message.title = object.title ?? "";
    return message;
  },
};

function createBaseStartConversationResponse(): StartConversationResponse {
  return { conversationId: "" };
}

export const StartConversationResponse: MessageFns<StartConversationResponse> = {
  encode(message: StartConversationResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.conversationId !== "") {
      writer.uint32(10).string(message.conversationId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StartConversationResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStartConversationResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.conversationId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StartConversationResponse {
    return {
      conversationId: isSet(object.conversationId)
        ? globalThis.String(object.conversationId)
        : isSet(object.conversation_id)
        ? globalThis.String(object.conversation_id)
        : "",
    };
  },

  toJSON(message: StartConversationResponse): unknown {
    const obj: any = {};
    if (message.conversationId !== "") {
      obj.conversationId = message.conversationId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StartConversationResponse>, I>>(base?: I): StartConversationResponse {
    return StartConversationResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StartConversationResponse>, I>>(object: I): StartConversationResponse {
    const message = createBaseStartConversationResponse();
    message.conversationId = object.conversationId ?? "";
    return message;
  },
};

function createBaseSendMessageRequest(): SendMessageRequest {
  return { conversationId: "", body: "" };
}

export const SendMessageRequest: MessageFns<SendMessageRequest> = {
  encode(message: SendMessageRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.conversationId !== "") {
      writer.uint32(10).string(message.conversationId);
    }
    if (message.body !== "") {
      writer.uint32(18).string(message.body);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SendMessageRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSendMessageRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.conversationId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.body = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SendMessageRequest {
    return {
      conversationId: isSet(object.conversationId)
        ? globalThis.String(object.conversationId)
        : isSet(object.conversation_id)
        ? globalThis.String(object.conversation_id)
        : "",
      body: isSet(object.body) ? globalThis.String(object.body) : "",
    };
  },

  toJSON(message: SendMessageRequest): unknown {
    const obj: any = {};
    if (message.conversationId !== "") {
      obj.conversationId = message.conversationId;
    }
    if (message.body !== "") {
      obj.body = message.body;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SendMessageRequest>, I>>(base?: I): SendMessageRequest {
    return SendMessageRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SendMessageRequest>, I>>(object: I): SendMessageRequest {
    const message = createBaseSendMessageRequest();
    message.conversationId = object.conversationId ?? "";
    message.body = object.body ?? "";
    return message;
  },
};

function createBaseSendMessageResponse(): SendMessageResponse {
  return { reply: "", tone: EmotionalTone.EMOTIONAL_TONE_UNSPECIFIED };
}

export const SendMessageResponse: MessageFns<SendMessageResponse> = {
  encode(message: SendMessageResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.reply !== "") {
      writer.uint32(10).string(message.reply);
    }
    if (message.tone !== EmotionalTone.EMOTIONAL_TONE_UNSPECIFIED) {
      writer.uint32(16).int32(emotionalToneToNumber(message.tone));
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SendMessageResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSendMessageResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.reply = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.tone = emotionalToneFromJSON(reader.int32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SendMessageResponse {
    return {
      reply: isSet(object.reply) ? globalThis.String(object.reply) : "",
      tone: isSet(object.tone) ? emotionalToneFromJSON(object.tone) : EmotionalTone.EMOTIONAL_TONE_UNSPECIFIED,
    };
  },

  toJSON(message: SendMessageResponse): unknown {
    const obj: any = {};
    if (message.reply !== "") {
      obj.reply = message.reply;
    }
    if (message.tone !== EmotionalTone.EMOTIONAL_TONE_UNSPECIFIED) {
      obj.tone = emotionalToneToJSON(message.tone);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SendMessageResponse>, I>>(base?: I): SendMessageResponse {
    return SendMessageResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SendMessageResponse>, I>>(object: I): SendMessageResponse {
    const message = createBaseSendMessageResponse();
    message.reply = object.reply ?? "";
    message.tone = object.tone ?? EmotionalTone.EMOTIONAL_TONE_UNSPECIFIED;
    return message;
  },
};

function createBaseEndConversationRequest(): EndConversationRequest {
  return { conversationId: "" };
}

export const EndConversationRequest: MessageFns<EndConversationRequest> = {
  encode(message: EndConversationRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.conversationId !== "") {
      writer.uint32(10).string(message.conversationId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EndConversationRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEndConversationRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.conversationId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EndConversationRequest {
    return {
      conversationId: isSet(object.conversationId)
        ? globalThis.String(object.conversationId)
        : isSet(object.conversation_id)
        ? globalThis.String(object.conversation_id)
        : "",
    };
  },

  toJSON(message: EndConversationRequest): unknown {
    const obj: any = {};
    if (message.conversationId !== "") {
      obj.conversationId = message.conversationId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EndConversationRequest>, I>>(base?: I): EndConversationRequest {
    return EndConversationRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EndConversationRequest>, I>>(object: I): EndConversationRequest {
    const message = createBaseEndConversationRequest();
    message.conversationId = object.conversationId ?? "";
    return message;
  },
};

function createBaseEndConversationResponse(): EndConversationResponse {
  return {};
}

export const EndConversationResponse: MessageFns<EndConversationResponse> = {
  encode(_: EndConversationResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EndConversationResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEndConversationResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): EndConversationResponse {
    return {};
  },

  toJSON(_: EndConversationResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<EndConversationResponse>, I>>(base?: I): EndConversationResponse {
    return EndConversationResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EndConversationResponse>, I>>(_: I): EndConversationResponse {
    const message = createBaseEndConversationResponse();
    return message;
  },
};

function createBaseGetHistoryRequest(): GetHistoryRequest {
  return { conversationId: "", limit: 0 };
}

export const GetHistoryRequest: MessageFns<GetHistoryRequest> = {
  encode(message: GetHistoryRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.conversationId !== "") {
      writer.uint32(10).string(message.conversationId);
    }
    if (message.limit !== 0) {
      writer.uint32(16).uint32(message.limit);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetHistoryRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetHistoryRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.conversationId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.limit = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetHistoryRequest {
    return {
      conversationId: isSet(object.conversationId)
        ? globalThis.String(object.conversationId)
        : isSet(object.conversation_id)
        ? globalThis.String(object.conversation_id)
        : "",
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : 0,
    };
  },

  toJSON(message: GetHistoryRequest): unknown {
    const obj: any = {};
    if (message.conversationId !== "") {
      obj.conversationId = message.conversationId;
    }
    if (message.limit !== 0) {
      obj.limit = Math.round(message.limit);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetHistoryRequest>, I>>(base?: I): GetHistoryRequest {
    return GetHistoryRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetHistoryRequest>, I>>(object: I): GetHistoryRequest {
    const message = createBaseGetHistoryRequest();
    message.conversationId = object.conversationId ?? "";
    message.limit = object.limit ?? 0;
    return message;
  },
};

function createBaseGetHistoryResponse(): GetHistoryResponse {
  return { messages: [] };
}

export const GetHistoryResponse: MessageFns<GetHistoryResponse> = {
  encode(message: GetHistoryResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.messages) {
      Message.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetHistoryResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetHistoryResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.messages.push(Message.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetHistoryResponse {
    return {
      messages: globalThis.Array.isArray(object?.messages) ? object.messages.map((e: any) => Message.fromJSON(e)) : [],
    };
  },

  toJSON(message: GetHistoryResponse): unknown {
    const obj: any = {};
    if (message.messages?.length) {
      obj.messages = message.messages.map((e) => Message.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetHistoryResponse>, I>>(base?: I): GetHistoryResponse {
    return GetHistoryResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetHistoryResponse>, I>>(object: I): GetHistoryResponse {
    const message = createBaseGetHistoryResponse();
    message.messages = object.messages?.map((e) => Message.fromPartial(e)) || [];
    return message;
  },
};

function createBaseListConversationsRequest(): ListConversationsRequest {
  return { userId: "", limit: 0 };
}

export const ListConversationsRequest: MessageFns<ListConversationsRequest> = {
  encode(message: ListConversationsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.limit !== 0) {
      writer.uint32(16).uint32(message.limit);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListConversationsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListConversationsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.limit = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListConversationsRequest {
    return {
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : 0,
    };
  },

  toJSON(message: ListConversationsRequest): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.limit !== 0) {
      obj.limit = Math.round(message.limit);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListConversationsRequest>, I>>(base?: I): ListConversationsRequest {
    return ListConversationsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListConversationsRequest>, I>>(object: I): ListConversationsRequest {
    const message = createBaseListConversationsRequest();
    message.userId = object.userId ?? "";
    message.limit = object.limit ?? 0;
    return message;
  },
};

function createBaseListConversationsResponse(): ListConversationsResponse {
  return { conversations: [] };
}

export const ListConversationsResponse: MessageFns<ListConversationsResponse> = {
  encode(message: ListConversationsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.conversations) {
      ConversationSummary.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListConversationsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListConversationsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.conversations.push(ConversationSummary.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListConversationsResponse {
    return {
      conversations: globalThis.Array.isArray(object?.conversations)
        ? object.conversations.map((e: any) => ConversationSummary.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ListConversationsResponse): unknown {
    const obj: any = {};
    if (message.conversations?.length) {
      obj.conversations = message.conversations.map((e) => ConversationSummary.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListConversationsResponse>, I>>(base?: I): ListConversationsResponse {
    return ListConversationsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListConversationsResponse>, I>>(object: I): ListConversationsResponse {
    const message = createBaseListConversationsResponse();
    message.conversations = object.conversations?.map((e) => ConversationSummary.fromPartial(e)) || [];
    return message;
  },
};

function createBaseMessage(): Message {
  return {
    id: "",
    role: Role.ROLE_UNSPECIFIED,
    body: "",
    tone: EmotionalTone.EMOTIONAL_TONE_UNSPECIFIED,
    sentAt: undefined,
  };
}

export const Message: MessageFns<Message> = {
  encode(message: Message, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.role !== Role.ROLE_UNSPECIFIED) {
      writer.uint32(16).int32(roleToNumber(message.role));
    }
    if (message.body !== "") {
      writer.uint32(26).string(message.body);
    }
    if (message.tone !== EmotionalTone.EMOTIONAL_TONE_UNSPECIFIED) {
      writer.uint32(32).int32(emotionalToneToNumber(message.tone));
    }
    if (message.sentAt !== undefined) {
      Timestamp.encode(toTimestamp(message.sentAt), writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Message {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.role = roleFromJSON(reader.int32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.body = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.tone = emotionalToneFromJSON(reader.int32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.sentAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Message {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      role: isSet(object.role) ? roleFromJSON(object.role) : Role.ROLE_UNSPECIFIED,
      body: isSet(object.body) ? globalThis.String(object.body) : "",
      tone: isSet(object.tone) ? emotionalToneFromJSON(object.tone) : EmotionalTone.EMOTIONAL_TONE_UNSPECIFIED,
      sentAt: isSet(object.sentAt)
        ? globalThis.String(object.sentAt)
        : isSet(object.sent_at)
        ? globalThis.String(object.sent_at)
        : undefined,
    };
  },

  toJSON(message: Message): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.role !== Role.ROLE_UNSPECIFIED) {
      obj.role = roleToJSON(message.role);
    }
    if (message.body !== "") {
      obj.body = message.body;
    }
    if (message.tone !== EmotionalTone.EMOTIONAL_TONE_UNSPECIFIED) {
      obj.tone = emotionalToneToJSON(message.tone);
    }
    if (message.sentAt !== undefined) {
      obj.sentAt = message.sentAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Message>, I>>(base?: I): Message {
    return Message.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Message>, I>>(object: I): Message {
    const message = createBaseMessage();
    message.id = object.id ?? "";
    message.role = object.role ?? Role.ROLE_UNSPECIFIED;
    message.body = object.body ?? "";
    message.tone = object.tone ?? EmotionalTone.EMOTIONAL_TONE_UNSPECIFIED;
    message.sentAt = object.sentAt ?? undefined;
    return message;
  },
};

function createBaseConversationSummary(): ConversationSummary {
  return {
    id: "",
    userId: "",
    title: "",
    status: ConversationStatus.CONVERSATION_STATUS_UNSPECIFIED,
    messageCount: 0,
    startedAt: undefined,
    endedAt: undefined,
  };
}

export const ConversationSummary: MessageFns<ConversationSummary> = {
  encode(message: ConversationSummary, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.userId !== "") {
      writer.uint32(18).string(message.userId);
    }
    if (message.title !== "") {
      writer.uint32(26).string(message.title);
    }
    if (message.status !== ConversationStatus.CONVERSATION_STATUS_UNSPECIFIED) {
      writer.uint32(32).int32(conversationStatusToNumber(message.status));
    }
    if (message.messageCount !== 0) {
      writer.uint32(40).uint32(message.messageCount);
    }
    if (message.startedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.startedAt), writer.uint32(50).fork()).join();
    }
    if (message.endedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.endedAt), writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ConversationSummary {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConversationSummary();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.status = conversationStatusFromJSON(reader.int32());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.messageCount = reader.uint32();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.startedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.endedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ConversationSummary {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      status: isSet(object.status)
        ? conversationStatusFromJSON(object.status)
        : ConversationStatus.CONVERSATION_STATUS_UNSPECIFIED,
      messageCount: isSet(object.messageCount)
        ? globalThis.Number(object.messageCount)
        : isSet(object.message_count)
        ? globalThis.Number(object.message_count)
        : 0,
      startedAt: isSet(object.startedAt)
        ? globalThis.String(object.startedAt)
        : isSet(object.started_at)
        ? globalThis.String(object.started_at)
        : undefined,
      endedAt: isSet(object.endedAt)
        ? globalThis.String(object.endedAt)
        : isSet(object.ended_at)
        ? globalThis.String(object.ended_at)
        : undefined,
    };
  },

  toJSON(message: ConversationSummary): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.status !== ConversationStatus.CONVERSATION_STATUS_UNSPECIFIED) {
      obj.status = conversationStatusToJSON(message.status);
    }
    if (message.messageCount !== 0) {
      obj.messageCount = Math.round(message.messageCount);
    }
    if (message.startedAt !== undefined) {
      obj.startedAt = message.startedAt;
    }
    if (message.endedAt !== undefined) {
      obj.endedAt = message.endedAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ConversationSummary>, I>>(base?: I): ConversationSummary {
    return ConversationSummary.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ConversationSummary>, I>>(object: I): ConversationSummary {
    const message = createBaseConversationSummary();
    message.id = object.id ?? "";
    message.userId = object.userId ?? "";
    message.title = object.title ?? "";
    message.status = object.status ?? ConversationStatus.CONVERSATION_STATUS_UNSPECIFIED;
    message.messageCount = object.messageCount ?? 0;
    message.startedAt = object.startedAt ?? undefined;
    message.endedAt = object.endedAt ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(dateStr: string): Timestamp {
  const date = new globalThis.Date(dateStr);
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): string {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis).toISOString();
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
